import React from 'react';
import './NewArrivals.css'; 
import 'bootstrap/dist/css/bootstrap.min.css';
const NewArrivals = () => {
  const cards = [
    {
      image: 'https://contentstatic.techgig.com/photo/75551562.cms',
      title: 'C Language',
      Disc: 'C is a general-purpose programming language, developed in 1972, and still quite popular.',
    },
    {
      image: 'https://bs-uploads.toptal.io/blackfish-uploads/components/blog_post_page/content/cover_image_file/cover_image/1309974/retina_1708x683_cover-0828_AfterAllTheseYearstheWorldisStillPoweredbyCProgramming_Razvan_Newsletter-2b9ea38294bb08c5aea1f0c1cb06732f.png',
      title: 'C++, .Net',
      Disc: 'C++ is a high-level, general-purpose programming language created by Danish computer scientist Bjarne Stroustrup',
    },
    {
      image: 'https://www.mtaeducation.in/images/courses/details/advancedjava.jpg',
      title: 'Adavance JAVA',
      Disc: 'Advance Java It is a part of Java programming language. It is an advanced technology to develop web-based applications.',
    },
    {
      image: 'https://www.castechnologies.co.in/Inner/Core%20Java.jpg',
      title: 'Core JAVA',
      Disc: 'Core Java is the part of Java SE where the developers develop desktop-based applications using the basic concepts of Java.',
    },
    {
      image: 'https://www.macworld.com/wp-content/uploads/2023/01/learn_python_mac.jpg?quality=50&strip=all',
      title: 'Python',
      Disc: 'Python is a high-level programming language that lets you work more efficiently and effectively.',
    },
    {
      image: 'https://miro.medium.com/v2/resize:fit:1358/1*cG6U1qstYDijh9bPL42e-Q.jpeg',
      title: 'Machine Learning',
      Disc: 'Machine learning is data driven technology. Large amount of data generated by organizations. ',
    },
    {
      image: 'https://ourworldindata.org/images/published/artificial-intelligence-featured-image.png',
      title: 'Artificial Intelligence',
      Disc: 'Artificial intelligence is the ability of a computer or computer-controlled robot to perform tasks',
    },
    {
      image: 'https://www.trickyenough.com/wp-content/uploads/2020/08/development-scaled.jpg',
      title: 'Front end Development',
      Disc: 'The development or creation of a user interface.',
    },
    {
      image: 'https://assets-global.website-files.com/606a802fcaa89bc357508cad/611432b386bb6d5c574f91f3_1.png',
      title: 'Back end development',
      Disc: 'Working on server-side software.',
    },
  ];

  return (
    <>
    <div className='title'>
        <h3 style={{color:"white"}}>
          <u>Computer Science courses</u>
        </h3>
        <hr className='hr1'></hr>
    </div>
    <div className="row">
        {cards.map((card, index) => (
          <div className="col-md-4" key={index}>
            <div className="card">
              <div className="card-image">
                <img src={card.image} alt={card.title} className="zoom-in" />
              </div>
              <div className="card-footer">
                <h5 className="card-title" >{card.title}</h5>
                <p className='links' style={{color:"black"}}>{card.Disc}</p>
              </div>
            </div>
          </div>
        ))}
      </div></>
  );
};

export default NewArrivals;